apiVersion: v1
kind: Service
metadata:
  name: watsoncloudant
  labels:
    app: watsoncloudant
spec:
  ports:
  - port: 8080
    targetPort: http-server
  selector:
    app: watsoncloudant
  type: NodePort